/*
AUTOGENERATED FILE. DO NOT EDIT.
MANUAL CHANGES WILL BE LOST.

Generated by tool: github.com/leshless/golibrary/enum_generator
Generated from source file: {{.FileName}}.go
*/

package {{.PackageName}}

{{- range .Enums}}

var {{.TypeName}}FromString = map[string]{{.TypeName}}{
{{- range .Constants}}
	"{{.StringValue}}": {{.Name}},
{{- end}}
}

var {{.TypeName}}ToString = map[{{.TypeName}}]string{
{{- range .Constants}}
	{{.Name}}: "{{.StringValue}}",
{{- end}}
}

func (e {{.TypeName}}) String() string {
	if str, ok := {{.TypeName}}ToString[e]; ok {
		return str
	}
    
	return {{.TypeName}}ToString[{{.DefaultConstantName}}]
}
{{- end}}