/*
AUTOGENERATED FILE. DO NOT EDIT.
MANUAL CHANGES WILL BE LOST.

Generated by tool: github.com/leshless/golibrary/constructor_generator
Generated from source file: {{.FileName}}
*/

package {{.PackageName}}
{{if .Imports}}
import (
	{{- range .Imports}}
	{{if .Name}}{{.Name}} {{end}}"{{.Path}}"
	{{- end}}
)
{{end}}
func {{.ConstructorName}}(
	{{- range $index, $field := .Fields}}
	{{$field.ArgName}} {{$field.Type}},
	{{- end}}
) {{if not .IsValueInstance}}*{{end}}{{.StructName}} {
	return {{if not .IsValueInstance}}&{{end}}{{.StructName}}{
		{{- range $field := .Fields}}
		{{$field.Name}}: {{$field.ArgName}},
		{{- end}}
	}
}