/*
AUTOGENERATED FILE. DO NOT EDIT.
MANUAL CHANGES WILL BE LOST.

Generated by tool: github.com/leshless/golibrary/constructor_generator
Generated from source file: /home/leshless/golibrary/chans/functions.go
*/

package chans

func newStruct1(
	jopa int,
) *struct1 {
	return &struct1{
		jopa: jopa,
	}
}
