/*
AUTOGENERATED FILE. DO NOT EDIT.
MANUAL CHANGES WILL BE LOST.

Generated by tool: github.com/leshless/golibrary/error_generator
Generated from source file: {{.FileName}}.go
*/

package {{.PackageName}}

import (
	"fmt"
)

{{range .Errors -}}
// {{.ConstructorName}} creates new {{.TypeName}} error
func {{.ConstructorName}}(
	{{- range $i, $field := .Fields}}
	{{$field.ArgName}} {{$field.Type}},
	{{- end}}
) error {
	return {{.TypeName}}{
		{{- range .Fields}}
		{{.Name}}: {{.ArgName}},
		{{- end}}
	}
}

var _ Error = {{.TypeName}}{}

// Error returns text representation of error
func (e {{.TypeName}}) Error() string {
	{{- if .TextSprintf}}
	return {{.TextSprintf}}
	{{- else}}
	return fmt.Sprintf("{{.TypeName}}{%s}",
		{{- range $i, $field := .Fields}}
		{{- if $i}} + ", " + {{end}}
		fmt.Sprintf("{{$field.Name}}:%v", e.{{$field.Name}})
		{{- end}}
	)
	{{- end}}
}

// Message returns user-friendly message
func (e {{.TypeName}}) Message() string {
	{{- if .MessageSprintf}}
	return {{.MessageSprintf}}
	{{- else}}
	// Fallback to Error() if no message template
	return e.Error()
	{{- end}}
}

// Code returns error code
func (e {{.TypeName}}) Code() Code {
	{{- if .CodeValue}}
	return {{.CodeValue}}
	{{- else}}
	return "UNKNOWN_ERROR"
	{{- end}}
}

// Unwrap returns underlying errors
func (e {{.TypeName}}) Unwrap() []error {
	var errs []error
	{{- range .Fields}}
	{{- if .IsError}}
	if e.{{.Name}} != nil {
		errs = append(errs, e.{{.Name}})
	}
	{{- end}}
	{{- end}}
	return errs
}

// Is checks if error is of type {{.TypeName}}
func (e {{.TypeName}}) Is(target error) bool {
	_, ok := target.({{.TypeName}})
	return ok
}

{{end}}
